epochs: 100
time_steps: 16
dim: 256
num_heads: 16
num_compartment: 2
in_channels: 2
patch_size: 16
mlp_ratio: 1
drop_path: 0.1
data_dir: /data/hyx/ViT-dend/data/cifar10-dvs/cifar10-dvs
dataset: cifar10-dvs
num_classes: 10
img_size: 128
crop_pct: 1.0
scale:
    - 1.0
    - 1.0
ratio: [0.2,1.0]
color_jitter: 0.
interpolation: bicubic
train_interpolation: bicubic
use_conv_as_linear: True
aa: rand-m9-n1-mstd0.4-inc1
model-ema: False
model-ema-decay: 0.9998
mixup: 0.5
mixup_off_epoch: 0
mixup_prob: 0.5
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 0.0
reprob: 0.25
remode: const
amp: True
batch_size: 16
val_batch_size: 16
decay_rate: 0.1
lr: 5e-3 #5e-3
min_lr: 1e-5
sched: cosine
weight_decay: 6e-2
cooldown_epochs: 10
warmup_epochs: 10
decay_epochs: 20
warmup_lr: 0.00001
opt: adamw
smoothing: 0.1
workers: 4
depths: 2
# TET
TET: True
TET_means: 1.0
TET_lamb: 0.001